
{.$DEFINE SIMULATE_SPI}                 // Skips over hardware loops in the SPI Code

{.$DEFINE DCCTIMER_DISABLE}             // Does not enable the DCC 56us Timer

{.$DEFINE UART_ENABLE}                  // Adds/Removes all UART Code from the build

{.$DEFINE PINCHANGE_INTERRUPT_ENABLE}   // Enables the Pin Change Interrupt

{.$DEFINE SPI_ENABLE}                   // Enables the SPI Module

